#!/bin/bash
clear
echo "=========================================================="
echo "   YOURLS 2026 - FULL STACK DEPLOYMENT (Alsunni Edition)  "
echo "=========================================================="

# 1. Interactive Input
read -p "Enter your Domain (e.g. qr.alsunniNet.com): " DOMAIN
read -p "Enter Database Name [yourls_db]: " DB_NAME
DB_NAME=${DB_NAME:-yourls_db}
read -p "Enter Database User [yourls_user]: " DB_USER
DB_USER=${DB_USER:-yourls_user}
read -sp "Enter Database Password: " DB_PASS
echo ""
read -p "Enter Admin Username: " ADMIN_USER
read -sp "Enter Admin Password: " ADMIN_PASS
echo -e "\n==========================================================\n"

# 2. System Update & Stack Install
echo "📦 Installing Apache, MariaDB, and PHP 8.3..."
sudo apt update && sudo apt upgrade -y
sudo apt install apache2 mariadb-server php php-mysql php-curl php-gd php-xml php-mbstring git unzip -y
sudo a2enmod rewrite ssl remoteip

# 3. Database Configuration
echo "🗄️  Setting up Database..."
sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
sudo mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
sudo mysql -e "FLUSH PRIVILEGES;"

# 4. SSL & Cloudflare Certificates
sudo mkdir -p /etc/apache2/ssl
echo "📜 PASTE your Cloudflare ORIGIN CERTIFICATE (PEM) then press Ctrl+D:"
cat | sudo tee /etc/apache2/ssl/yourls.pem > /dev/null
echo "🔑 PASTE your Cloudflare PRIVATE KEY then press Ctrl+D:"
cat | sudo tee /etc/apache2/ssl/yourls.key > /dev/null

# 5. Apache Virtual Host with Security Headers
echo "🌐 Configuring Web Server..."
cat <<EOF | sudo tee /etc/apache2/sites-available/yourls.conf
<VirtualHost *:80>
    ServerName $DOMAIN
    Redirect permanent / https://$DOMAIN/
</VirtualHost>

<VirtualHost *:443>
    ServerName $DOMAIN
    DocumentRoot /var/www/html
    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/yourls.pem
    SSLCertificateKeyFile /etc/apache2/ssl/yourls.key
    RemoteIPHeader CF-Connecting-IP

    <Directory /var/www/html>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
EOF

sudo a2ensite yourls.conf
sudo a2dissite 000-default.conf
echo "AllowEncodedSlashes On" | sudo tee -a /etc/apache2/apache2.conf

# 6. Deploy YOURLS Core
echo "📥 Downloading YOURLS Core..."
cd /var/www/html
sudo rm -rf *
sudo git clone https://github.com/YOURLS/YOURLS.git .

# 7. Generate Secure config.php
echo "🛠️  Building config.php from scratch..."
COOKIE_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

cat <<EOF | sudo tee /var/www/html/user/config.php > /dev/null
<?php
/** YOURLS Config Generated by Alsunni One-Click Deploy **/

// Cloudflare HTTPS Fix
if (isset(\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    \$_SERVER['HTTPS'] = 'on';
}

define( 'YOURLS_DB_USER', '$DB_USER' );
define( 'YOURLS_DB_PASS', '$DB_PASS' );
define( 'YOURLS_DB_NAME', '$DB_NAME' );
define( 'YOURLS_DB_HOST', 'localhost' );
define( 'YOURLS_DB_PREFIX', 'yourls_' );
define( 'YOURLS_SITE', 'https://$DOMAIN' );
define( 'YOURLS_HOURS_OFFSET', 0 ); 
define( 'YOURLS_UNIQUE_URLS', true );
define( 'YOURLS_PRIVATE', true );
define( 'YOURLS_COOKIEKEY', '$COOKIE_KEY' );

\$yourls_user_passwords = array(
    '$ADMIN_USER' => '$ADMIN_PASS'
);

// Character Set: Base 62 (Supports Hyphens)
define( 'YOURLS_URL_CONVERT', 62 );
\$yourls_reserved_URL = array( 'admin', 'about', 'contact', 'sample' );
EOF

# 8. Install Add-ons (Plugins)
echo "🔌 Installing 2026-Standard Add-ons..."
cd /var/www/html/user/plugins
sudo git clone https://github.com/YOURLS/sample-qrcode.git qrcode
sudo git clone https://github.com/williambargentball/YOURLS-Forward-Slash-In-Urls.git slashes
sudo git clone https://github.com/ozh/yourls-fallback-url.git fallback
sudo git clone https://github.com/gioxx/YOURLS-LogoSuite.git logosuite

# 9. Final Permissions & Clean-up
echo "🔑 Hardening Permissions..."
sudo chown -R www-data:www-data /var/www/html
sudo systemctl restart apache2

echo "=========================================================="
echo "✅ DEPLOYMENT COMPLETE!"
echo "Site: https://$DOMAIN/admin/"
echo "Instructions: Login and activate your 4 new plugins."
echo "=========================================================="
