#!/bin/bash
clear
echo "=========================================================="
echo "   YOURLS 2026 - FULL STACK DEPLOYMENT (Alsunni Edition)  "
echo "=========================================================="

# 1. Interactive Input
read -p "Enter your Domain (e.g. qr.alsunniNet.com): " DOMAIN
read -p "Enter Database Name [yourls_db]: " DB_NAME
DB_NAME=${DB_NAME:-yourls_db}
read -p "Enter Database User [yourls_user]: " DB_USER
DB_USER=${DB_USER:-yourls_user}
read -sp "Enter Database Password: " DB_PASS
echo ""
read -p "Enter YOURLS Admin Username: " ADMIN_USER
read -sp "Enter YOURLS Admin Password: " ADMIN_PASS
echo ""
read -p "Enter Cloudflare API Token (for DDNS): " CF_TOKEN
read -p "Enter Cloudflare Zone ID: " CF_ZONE_ID
echo -e "\n==========================================================\n"

# 2. System Update & Stack Install
echo "📦 Installing Apache, MariaDB, and PHP 8.3..."
sudo apt update && sudo apt upgrade -y
sudo apt install apache2 mariadb-server php php-mysql php-curl php-gd php-xml php-mbstring git unzip -y
sudo a2enmod rewrite ssl remoteip

# 3. Database Configuration
echo "🗄️  Setting up Database..."
sudo mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
sudo mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
sudo mysql -e "FLUSH PRIVILEGES;"

# 4. SSL & Cloudflare Certificates
sudo mkdir -p /etc/apache2/ssl
echo "📜 PASTE your Cloudflare ORIGIN CERTIFICATE (PEM) then press Ctrl+D:"
cat | sudo tee /etc/apache2/ssl/yourls.pem > /dev/null
echo "🔑 PASTE your Cloudflare PRIVATE KEY then press Ctrl+D:"
cat | sudo tee /etc/apache2/ssl/yourls.key > /dev/null

# 5. Apache Virtual Host
echo "🌐 Configuring Web Server..."
cat <<EOF | sudo tee /etc/apache2/sites-available/yourls.conf
<VirtualHost *:80>
    ServerName $DOMAIN
    Redirect permanent / https://$DOMAIN/
</VirtualHost>

<VirtualHost *:443>
    ServerName $DOMAIN
    DocumentRoot /var/www/html
    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/yourls.pem
    SSLCertificateKeyFile /etc/apache2/ssl/yourls.key
    RemoteIPHeader CF-Connecting-IP

    <Directory /var/www/html>
        Options -Indexes
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
EOF

sudo a2ensite yourls.conf
sudo a2dissite 000-default.conf
echo "AllowEncodedSlashes On" | sudo tee -a /etc/apache2/apache2.conf

# 6. Deploy YOURLS Core
echo "📥 Downloading YOURLS Core..."
cd /var/www/html
sudo rm -rf *
sudo git clone https://github.com/YOURLS/YOURLS.git .

# 7. Generate Secure config.php
echo "🛠️  Building config.php..."
COOKIE_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

cat <<EOF | sudo tee /var/www/html/user/config.php > /dev/null
<?php
/** YOURLS Config Generated by Alsunni One-Click Deploy **/

if (isset(\$_SERVER['HTTP_X_FORWARDED_PROTO']) && \$_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    \$_SERVER['HTTPS'] = 'on';
}

define( 'YOURLS_DB_USER', '$DB_USER' );
define( 'YOURLS_DB_PASS', '$DB_PASS' );
define( 'YOURLS_DB_NAME', '$DB_NAME' );
define( 'YOURLS_DB_HOST', 'localhost' );
define( 'YOURLS_DB_PREFIX', 'yourls_' );
define( 'YOURLS_SITE', 'https://$DOMAIN' );
define( 'YOURLS_HOURS_OFFSET', 0 ); 
define( 'YOURLS_UNIQUE_URLS', true );
define( 'YOURLS_PRIVATE', true );
define( 'YOURLS_COOKIEKEY', '$COOKIE_KEY' );

\$yourls_user_passwords = array(
    '$ADMIN_USER' => '$ADMIN_PASS'
);

define( 'YOURLS_URL_CONVERT', 62 );
\$yourls_reserved_URL = array( 'admin', 'about', 'contact' );
EOF

# 8. Install Add-ons (Plugins)
echo "🔌 Installing Expanded Plugin Suite..."
cd /var/www/html/user/plugins
sudo git clone https://github.com/YOURLS/sample-qrcode.git qrcode
sudo git clone https://github.com/williambargentball/YOURLS-Forward-Slash-In-Urls.git slashes
sudo git clone https://github.com/ozh/yourls-fallback-url.git fallback
sudo git clone https://github.com/gioxx/YOURLS-LogoSuite.git logosuite
sudo git clone https://github.com/GautamGupta/YOURLS-Import-Export.git import-export
sudo git clone https://github.com/timcrockford/302-instead.git redirect-302
sudo git clone https://github.com/josheby/yourls-additional-charsets.git additional-charsets
sudo git clone https://github.com/neanrie/yourls.frontend-links.git frontend-links
sudo git clone https://github.com/Pacmoney22/yourls-white-label.git white-label

# 9. Cloudflare DDNS Setup
echo "☁️  Setting up Automatic IP Updater..."
cat <<EOF | sudo tee /usr/local/bin/cloudflare-ddns.sh > /dev/null
#!/bin/bash
TOKEN="$CF_TOKEN"
ZONE_ID="$CF_ZONE_ID"
RECORD_NAME="$DOMAIN"
CURRENT_IP=\$(curl -s https://ipv4.icanhazip.com)
RECORD_DATA=\$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/\$ZONE_ID/dns_records?name=\$RECORD_NAME" -H "Authorization: Bearer \$TOKEN" -H "Content-Type: application/json")
RECORD_ID=\$(echo \$RECORD_DATA | grep -oP '(?<="id":")[^"]*' | head -n 1)
OLD_IP=\$(echo \$RECORD_DATA | grep -oP '(?<="content":")[^"]*' | head -n 1)

if [ "\$CURRENT_IP" != "\$OLD_IP" ] && [ ! -z "\$RECORD_ID" ]; then
    curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/\$ZONE_ID/dns_records/\$RECORD_ID" -H "Authorization: Bearer \$TOKEN" -H "Content-Type: application/json" --data "{\\"type\\":\\"A\\",\\"name\\":\\"\$RECORD_NAME\\",\\"content\\":\\"\$CURRENT_IP\\",\\"ttl\\":1,\\"proxied\\":true}"
    echo "\$(date): IP updated to \$CURRENT_IP" >> /var/log/cloudflare-ddns.log
fi
EOF
sudo chmod +x /usr/local/bin/cloudflare-ddns.sh
(crontab -l 2>/dev/null; echo "*/5 * * * * /usr/local/bin/cloudflare-ddns.sh") | crontab -

# 10. Security: Root Redirect & Branded 404
echo "🔒 Finishing Security & Branding..."
cat <<EOF | sudo tee /var/www/html/index.php > /dev/null
<?php header("Location: https://$DOMAIN/admin/"); exit; ?>
EOF

cat <<EOF | sudo tee /var/www/html/404.php > /dev/null
<?php header("HTTP/1.1 404 Not Found"); ?>
<!DOCTYPE html><html><head><title>404 Not Found</title><style>body{font-family:sans-serif;text-align:center;padding:50px;background:#f9f9f9}div{background:white;padding:40px;border-radius:10px;display:inline-block;box-shadow:0 5px 15px rgba(0,0,0,0.1)}h1{color:#e74c3c}a{color:#3498db;text-decoration:none}</style></head>
<body><div><h1>404 - Link Not Found</h1><p>This short link is no longer active.</p><a href="https://$DOMAIN/admin/">Go to Dashboard</a></div></body></html>
EOF
echo "ErrorDocument 404 /404.php" | sudo tee -a /var/www/html/.htaccess

# 11. Final Permissions & Restart
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html
sudo systemctl restart apache2

echo "=========================================================="
echo "✅ DEPLOYMENT COMPLETE!"
echo "Site: https://$DOMAIN/admin/"
echo "New Plugins: White-Label and Frontend-Links added."
echo "=========================================================="
